// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEftHvvyDqnObcP8cTyT2c_XOw7bIdam0',
    appId: '1:864766329035:web:120797d911863c8f88db4e',
    messagingSenderId: '864766329035',
    projectId: 'nearme-ace8f',
    authDomain: 'nearme-ace8f.firebaseapp.com',
    storageBucket: 'nearme-ace8f.firebasestorage.app',
    measurementId: 'G-FBE5D351RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAVNTULbIoFFsNOen4xblfBCFg9iebaI',
    appId: '1:864766329035:android:0ae2aaed9b03743788db4e',
    messagingSenderId: '864766329035',
    projectId: 'nearme-ace8f',
    storageBucket: 'nearme-ace8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh80VSsdspJsmsnPPXzWUZBD1vwNEqTKs',
    appId: '1:864766329035:ios:a13d9019764e2df688db4e',
    messagingSenderId: '864766329035',
    projectId: 'nearme-ace8f',
    storageBucket: 'nearme-ace8f.firebasestorage.app',
    iosBundleId: 'io.mhsh.nearme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh80VSsdspJsmsnPPXzWUZBD1vwNEqTKs',
    appId: '1:864766329035:ios:a13d9019764e2df688db4e',
    messagingSenderId: '864766329035',
    projectId: 'nearme-ace8f',
    storageBucket: 'nearme-ace8f.firebasestorage.app',
    iosBundleId: 'io.mhsh.nearme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEftHvvyDqnObcP8cTyT2c_XOw7bIdam0',
    appId: '1:864766329035:web:39cfe6e3cb69ff4088db4e',
    messagingSenderId: '864766329035',
    projectId: 'nearme-ace8f',
    authDomain: 'nearme-ace8f.firebaseapp.com',
    storageBucket: 'nearme-ace8f.firebasestorage.app',
    measurementId: 'G-7WN8SRJ4BN',
  );
}
